##############################################################################
#
# Makefile
#
# This Makefile calls the Makefiles for command and telemetry ground control
# backend. Yes, it's recursive.
#
# -------------------------------------------------------------------------- #
#
# Benjamin Spencer
# ASEN 4018
# Project HEPCATS
# Subsystem: C&DH
# Created: February 12, 2018
# 
###############################################################################
cmd:
	make -f make/Makefile.cmd
tlm:
	make -f make/Makefile.tlm