write: write_main.c open_port.c port_config.c
	gcc -o write_main write_main.c open_port.c port_config.c

read: read_main.c open_port.c port_config.c
	gcc -o read_main read_main.c open_port.c port_config.c