sgs_cmd_sim_ieu: sgs_cmd_sim_ieu.c cmd_str_interp.c crt_telecmd_pkt.c get_doy.c write_buffer.c open_port.c port_config.c
	gcc -o sgs_cmd_sim_ieu sgs_cmd_sim_ieu.c cmd_str_interp.c crt_telecmd_pkt.c get_doy.c write_buffer.c open_port.c port_config.c

clean:
	rm sgs_cmd_sim_ieu