gc_prompt: gc_prompt_interp.c gc_macro_cmd.c gc_cmd_str_interp.c gc_crt_telecmd_pkt.c gc_open_port.c gc_port_config.c gc_write_buffer.c get_doy.c
	gcc -o gc_prompt gc_prompt_interp.c gc_macro_cmd.c gc_cmd_str_interp.c gc_crt_telecmd_pkt.c gc_open_port.c gc_port_config.c gc_write_buffer.c get_doy.c

clean:
	rm gc_prompt