sim_ieu_rcv_sgs_cmd: sim_ieu_rcv_sgs_cmd.c open_port.c port_config.c read_buffer.c telecmd_pkt_proc.c
	gcc -o sim_ieu_rcv_sgs_cmd sim_ieu_rcv_sgs_cmd.c open_port.c port_config.c read_buffer.c telecmd_pkt_proc.c
clean:
	rm sim_ieu_rcv_sgs_cmd