sim_ieu: sim_ieu sim_ieu.c sim_ieu_open_port.c sim_ieu_port_config.c sim_ieu_read_buffer.c sim_ieu_telecmd_pkt_proc.c
	gcc -o sim_ieu sim_ieu.c sim_ieu_open_port.c sim_ieu_port_config.c sim_ieu_read_buffer.c sim_ieu_telecmd_pkt_proc.c
clean:
	rm sim_ieu